### ISSUE TITLE
Server side auto exit problem

### ISSUE THREAD

**Issue by zhenpingfeng** [ihciah/shadow-tls#2]
After using it for a while, the server side shadow-tls automatically exits without an error message. Usually happens when loading a lot of pictures, or loading a lot of unread telegram messages (seems like it happened when loading lots of small chunks of data).

**Comment by zhenpingfeng** [comment]
During the test, the client side shadow-tls also has automatically exit problem.

**Comment by ihciah** [comment]
1. Please check system log and see if this problem caused by oom(`dmesg -T`)? It allocates 8K memory for each active connection.
2. Check if your io_uring related things(like memlock) is correctly configured(you may find them in monoio docs).

You can paste your related log here with you kernel version.

**Comment by zhenpingfeng** [comment]
server: 
![image](https://user-images.githubusercontent.com/13215166/186842962-5d0310a4-a481-498c-82ac-4fb0b4a551b9.png)

client:
![image](https://user-images.githubusercontent.com/13215166/186842750-bcc86ed2-6582-47ce-abdc-a2de227bbecb.png)
my client side has 128GB memory, which shouldn't be caused by oom.

**Comment by ihciah** [comment]
Ok I see. There seems a bug when accept connections. Once accept failed, it will return and stop the thread. When all threads goes down, it will exit.
